#!/usr/bin/env sh

unamekernel="$(uname -s)"

case "${unamekernel}" in
  MINGW64*)
    dir="$(readlink -f "$0"|xargs -d '\n' dirname)"
    jarfiles="$(find "${dir}/dist" -name *.jar | tr '\n' ':')"
    jarfiles=${jarfiles%?}
    ;;
  *)
    if [ -L $0 ];then
      dir=`readlink -f $0|xargs dirname`
    else
      dir=`dirname $0`
    fi
    jarfiles="$dir/dist/*"
    ;;
esac

java -ea -cp "$jarfiles" com.ka.spreadsheet.diff.SpreadSheetDiffer "$@"
